apiVersion: v1
kind: Service
metadata:
  name: image-dashboard
  labels:
    app: image-dashboard
    tier: management
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: image-dashboard
    tier: management
  type: NodePort
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: image-dashboard
spec:
  selector:
    matchLabels:
      app: image-dashboard
      tier: management
  replicas: 1
  template:
    metadata:
      labels:
        app: image-dashboard
        tier: management
    spec:
      containers:
      - name: image-dashboard
        image: gitcommit/k8s-image-dashboard:latest
        env:
         - name: REPO_REGEX
           value: gitcommit\/([a-zA-Z0-9-_]+):(.*)$|https://github.com/victorboissiere/$1/tree/$2
        resources:
          limits:
            memory: 200M
        readinessProbe:
          httpGet:
            path: /health
            port: web-dashboard
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: web-dashboard
          initialDelaySeconds: 5
          periodSeconds: 30
        ports:
        - name: web-dashboard
          containerPort: 3000
